[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 20000
via_ir = true

[profile.default.fuzz]
runs = 10000

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC}"
base = "${BASE_MAINNET_RPC}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
